In [27]:
import pandas as pd
import numpy as np


Parte 1: Numpy:
Para los ejercicios siguiente genere el código que considere
para resolver el problema que se le plantea.

1) ¿Cuál es el tamaño en bytes de un array de 1000 elementos de tipo booleano?

In [28]:
import sys

elements = [False] * 1000
bytes = sys.getsizeof(elements)
print(bytes)

8056


    2.Cree un array cuyos elementos sean los enteros pares en [1,100] y en orden decreciente. Muestre los 10 últimos por pantalla.

In [29]:
even_arr = np.arange(100, 0, -2)
print(even_arr)
print(even_arr[-10:])

[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66
  64  62  60  58  56  54  52  50  48  46  44  42  40  38  36  34  32  30
  28  26  24  22  20  18  16  14  12  10   8   6   4   2]
[20 18 16 14 12 10  8  6  4  2]


3)  Dado el array
    2 4 5 6
    0 3 7 4
    8 8 5 2
    1 5 6 1
Seleccione con una instrucción el subarray de elementos 0 3 7 4 Después, seleccione el subarray de elementos
    2 5
    8 5

In [62]:
matrix = np.array([ [2,4,5,6],
                    [0,3,7,4],
                    [8,8,5,2],
                    [1,5,6,1]
                    ])
print(matrix)

print("Subarray 0374")
print(matrix[1, : ])
print(matrix[  [0,2] ]  )
print(matrix[  [0,2],[[0,2], [2,1]] ]  )


[[2 4 5 6]
 [0 3 7 4]
 [8 8 5 2]
 [1 5 6 1]]
Subarray 0374
[0 3 7 4]
[[2 4 5 6]
 [8 8 5 2]]
[[2 5]
 [5 8]]
